version: '3'

services:
    wordpress:
        build: .
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        
    mariadb:
        image: mariadb:latest
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress
    
    redis:
        image: redis